version: "3.4"
services:
  centos7systemdbuild:
    cap_add:
      - SYS_ADMIN
    privileged: true
    user: root
    volumes:
      - rpms:/root/rpmbuild/SRPMS
      - rpm7:/root/rpmbuild/RPMS
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
