FROM aursu/centos:7-systemd

USER root
RUN yum -y --enablerepo=bintray-custom install \
        curl \
        dbus \
        systemd \
        util-linux \
    && yum clean all && rm -rf /var/cache/yum
