FROM aursu/rpmbuild:7-build-systemd

USER root
RUN yum -y --enablerepo=bintray-custom install \
        curl \
        dbus \
        systemd \
        util-linux \
    && yum clean all && rm -rf /var/cache/yum

RUN passwd -d root \
    && sed -i 's/nullok_secure/nullok/' /etc/pam.d/system-auth
