version: "3.4"
services:
  centos7systemdbuild:
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    user: root
    tmpfs:
      - /run
      - /tmp
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    build:
      context: .

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
